spring:
  datasource:
    generate-unique-name: false
  #    url: jdbc:h2:./devdb
#    username: sa
#    password: sa
  jpa:
    hibernate:
      ddl-auto: update

    properties:
      javax:
        persistence:
          validation:
            mode: none

