spring:
  datasource:
    generate-unique-name: false

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      javax:
        persistence:
          validation:
            mode: none

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100